import { Inter } from "next/font/google";
import "./globals.css";
// import { SessionProvider } from "next-auth/react"  // can only uuse in client
import Sessionwrap from "./component/sessionwrap";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Sessionwrap>
      <body className={inter.className}>{children}</body>
      </Sessionwrap>
    </html>
  );
}
